### ISSUE TITLE
Create Volume do not work in ScaleIO 1.32

### ISSUE THREAD

**Issue by swevm** [swevm/scaleio-py#21]
Example code, create_map-volume.py do not work with ScaleIO 1.32. The error message say StoragePoolId is needed to create a Volume in 1.32. Worked fine in 1.31 with specifying only ProtectionDomainID. 
I wonder if there´s a list of API call that have changed in 1.32?
Most likely adding StoragePoolId to API calls result in 1.31 and 1.32 working.

Error message:
earth:examples swevm$ python create_map-volume.py 192.168.102.12 admin Scaleio123 testvol01 default
2015-06-06 19:35:29,825: ERROR scaleio:_do_post | _do_post() - HTTP response error: 400
2015-06-06 19:35:29,825: ERROR scaleio:_do_post | _do_post() - HTTP response error, data: {"message":"Request message is not valid: The following parameter(s) must be part of the request body: storagePoolId.","httpStatusCode":400,"errorCode":0}
2015-06-06 19:35:29,826: ERROR scaleio:_do_post | _do_post() - Unhandled Error Occurred: cannot concatenate 'str' and 'int' objects
Traceback (most recent call last):
  File "create_map-volume.py", line 13, in <module>
    sio.create_volume(sys.argv[4], 8192, sio.get_pd_by_name(sys.argv[5]), mapAll=True)
  File "build/bdist.macosx-10.10-intel/egg/scaleiopy/scaleio.py", line 1132, in create_volume
  File "build/bdist.macosx-10.10-intel/egg/scaleiopy/scaleio.py", line 605, in _do_post
RuntimeError: _do_post() - Communication error with ScaleIO gateway

**Comment by swevm** [comment]
Fixed in #27
